#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on March 24, 2022 at 16:52:52.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[608];
extern c_float ldata[1218];
extern c_float udata[1218];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[608];
extern c_float Dinvscaling[608];
extern c_float Escaling[1218];
extern c_float Einvscaling[1218];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1826];
extern c_int linsys_solver_P[1826];
extern c_float linsys_solver_bp[1826];
extern c_float linsys_solver_sol[1826];
extern c_float linsys_solver_rho_inv_vec[1218];
extern c_int linsys_solver_Pdiag_idx[248];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[366];
extern c_int linsys_solver_AtoKKT[2897];
extern c_int linsys_solver_rhotoKKT[1218];
extern QDLDL_float linsys_solver_D[1826];
extern QDLDL_int linsys_solver_etree[1826];
extern QDLDL_int linsys_solver_Lnz[1826];
extern QDLDL_int   linsys_solver_iwork[5478];
extern QDLDL_bool  linsys_solver_bwork[1826];
extern QDLDL_float linsys_solver_fwork[1826];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[608];
extern c_float ysolution[1218];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[1218];
extern c_float work_rho_inv_vec[1218];
extern c_int work_constr_type[1218];
extern c_float work_x[608];
extern c_float work_y[1218];
extern c_float work_z[1218];
extern c_float work_xz_tilde[1826];
extern c_float work_x_prev[608];
extern c_float work_z_prev[1218];
extern c_float work_Ax[1218];
extern c_float work_Px[608];
extern c_float work_Aty[608];
extern c_float work_delta_y[1218];
extern c_float work_Atdelta_y[608];
extern c_float work_delta_x[608];
extern c_float work_Pdelta_x[608];
extern c_float work_Adelta_x[1218];
extern c_float work_D_temp[608];
extern c_float work_D_temp_A[608];
extern c_float work_E_temp[1218];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
